name: Windows arm64 CI (clangarm64)

on: [push, pull_request]

jobs:
  build-clangarm64:
    name: Build Windows (clangarm64)
    runs-on: windows-11-arm

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: clangarm64
        install: >-
          base-devel
          mingw-w64-clang-aarch64-gcc-compat
          mingw-w64-clang-aarch64-cmake
          mingw-w64-clang-aarch64-meson
          mingw-w64-clang-aarch64-ninja
          mingw-w64-clang-aarch64-glslang
          mingw-w64-clang-aarch64-spirv-tools
          mingw-w64-clang-aarch64-SDL2
          mingw-w64-clang-aarch64-vulkan-headers
          mingw-w64-clang-aarch64-vulkan-loader
          mingw-w64-clang-aarch64-freetype
          mingw-w64-clang-aarch64-flac
          mingw-w64-clang-aarch64-libmad
          mingw-w64-clang-aarch64-libogg
          mingw-w64-clang-aarch64-libvorbis
          mingw-w64-clang-aarch64-opus
          mingw-w64-clang-aarch64-opusfile
          mingw-w64-clang-aarch64-mpg123
          mingw-w64-clang-aarch64-libxmp
          mingw-w64-clang-aarch64-rlottie

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build vkQuake
      run: meson setup build --buildtype=release && ninja -C build

    - name: Upload vkQuake
      uses: actions/upload-artifact@v4
      with:
        name: vkQuake archive (clangarm64)
        path: build/vkquake.exe
